name: "Action 2"
description: "Just an action that prints an input"

inputs:
  same-input:
    description: "This is a normal input"
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        echo ${{ inputs.same-input }}
      shell: bash
      
    - run: |
        echo "sameinput=${{ inputs.same-input }}" >> $GITHUB_ENV
      shell: bash
      
    - run: |
        echo ${{ env.same-input }}
      shell: bash
